### ISSUE TITLE
fix refreshtasks.py: not authorized

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-api#87]
```
An error occurred (AccessDeniedException) when calling the ListTaskDefinitions operation: User: arn:aws:iam::636774461479:user/osp-api is not authorized to perform: ecs:ListTaskDefinitions on resource: *

Traceback (most recent call last):

  File "taskrefresh.py", line 21, in <module>

    ['aws', 'ecs', 'list-task-definitions'],

  File "/opt/python/3.5.3/lib/python3.5/subprocess.py", line 316, in check_output

    **kwargs).stdout

  File "/opt/python/3.5.3/lib/python3.5/subprocess.py", line 398, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['aws', 'ecs', 'list-task-definitions']' returned non-zero exit status 255

The command "./deploy.sh" exited with 1.
```

**Comment by lily-mayfield** [comment]
fixed in v0.9.3
